version: '3.8'

services:
  app:
    image: python:3.11-slim
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python app.py"
    volumes:
      - ./:/app
    environment:
      - FLASK_PORT=5000
      - PYTHONUNBUFFERED=1
    networks:
      - loop9Net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=loop9Net"
        - "traefik.http.routers.lfimoveis-http.rule=Host(`lfimoveis.loop9.com.br`)"
        - "traefik.http.routers.lfimoveis-http.entrypoints=web"
        - "traefik.http.routers.lfimoveis-http.middlewares=redirect-to-https"
        - "traefik.http.routers.lfimoveis.rule=Host(`lfimoveis.loop9.com.br`)"
        - "traefik.http.routers.lfimoveis.entrypoints=websecure"
        - "traefik.http.routers.lfimoveis.tls.certresolver=letsencrypt"
        - "traefik.http.services.lfimoveis.loadbalancer.server.port=5000"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  loop9Net:
    external: true
